require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by Active Record
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  
  # Open a Pry session
  Pry.start
end

# start the server
task :server do
  exec "rerun -b 'rackup config.ru -p 8000'" # rerun is a gem that restarts the server when you make changes to your code
end
